/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PROJECT4;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author HP
 */
public class project4 extends javax.swing.JFrame {
    DefaultListModel<String> tugasModel = new DefaultListModel<>();
    ArrayList<String> daftarTugas = new ArrayList<>();

    /**
     * Creates new form project4
     */
    public project4() {
        initComponents();
        listtugas.setModel(tugasModel);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        paneltambahtugas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ftmatkul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ftdead = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnhapus = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ftdetail = new javax.swing.JTextArea();
        paneldaftartugas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listtugas = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fdetail = new javax.swing.JTextArea();
        btnbersih = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(142, 172, 205));
        jTabbedPane1.setForeground(new java.awt.Color(249, 243, 204));
        jTabbedPane1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N

        paneltambahtugas.setBackground(new java.awt.Color(142, 172, 205));
        paneltambahtugas.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 243, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(paneltambahtugas);
        jLabel1.setText("Tambah Tugas Baru");
        paneltambahtugas.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(142, 172, 205));
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setBackground(new java.awt.Color(142, 172, 205));
        jPanel2.setLayout(new java.awt.GridLayout(3, 0, 0, 10));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 243, 204));
        jLabel2.setLabelFor(ftmatkul);
        jLabel2.setText("Nama Mata Kuliah :");
        jPanel2.add(jLabel2);

        ftmatkul.setBackground(new java.awt.Color(210, 224, 251));
        ftmatkul.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        ftmatkul.setForeground(new java.awt.Color(0, 172, 205));
        jPanel2.add(ftmatkul);

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 243, 204));
        jLabel3.setLabelFor(ftdead);
        jLabel3.setText("Deadline Tugas :");
        jPanel2.add(jLabel3);

        ftdead.setBackground(new java.awt.Color(210, 224, 251));
        ftdead.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        ftdead.setForeground(new java.awt.Color(0, 172, 205));
        jPanel2.add(ftdead);

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(249, 243, 204));
        jLabel4.setLabelFor(ftdetail);
        jLabel4.setText("Detail Tugas :");
        jPanel2.add(jLabel4);

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(142, 172, 205));

        btnhapus.setBackground(new java.awt.Color(249, 243, 204));
        btnhapus.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(142, 172, 205));
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnsimpan.setBackground(new java.awt.Color(249, 243, 204));
        btnsimpan.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(142, 172, 205));
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        ftdetail.setBackground(new java.awt.Color(210, 224, 251));
        ftdetail.setColumns(20);
        ftdetail.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        ftdetail.setForeground(new java.awt.Color(0, 172, 205));
        ftdetail.setRows(5);
        jScrollPane1.setViewportView(ftdetail);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnhapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnsimpan)))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhapus)
                    .addComponent(btnsimpan))
                .addContainerGap())
        );

        jPanel1.add(jPanel3);

        paneltambahtugas.add(jPanel1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Tambah Tugas", paneltambahtugas);

        paneldaftartugas.setBackground(new java.awt.Color(142, 172, 205));
        paneldaftartugas.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(249, 243, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setLabelFor(paneldaftartugas);
        jLabel5.setText("Daftar Tugas");
        paneldaftartugas.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(142, 172, 205));
        jPanel4.setLayout(new java.awt.GridLayout(4, 0));

        listtugas.setBackground(new java.awt.Color(210, 224, 251));
        listtugas.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        listtugas.setForeground(new java.awt.Color(0, 172, 205));
        listtugas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listtugasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        listtugas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listtugasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listtugas);

        jPanel4.add(jScrollPane2);

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 243, 204));
        jLabel6.setLabelFor(fdetail);
        jLabel6.setText("Detail Tugas :");
        jPanel4.add(jLabel6);

        fdetail.setEditable(false);
        fdetail.setBackground(new java.awt.Color(210, 224, 251));
        fdetail.setColumns(20);
        fdetail.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        fdetail.setForeground(new java.awt.Color(0, 172, 205));
        fdetail.setRows(5);
        jScrollPane3.setViewportView(fdetail);

        jPanel4.add(jScrollPane3);

        btnbersih.setBackground(new java.awt.Color(249, 243, 204));
        btnbersih.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnbersih.setForeground(new java.awt.Color(142, 172, 205));
        btnbersih.setText("Bersihkan");
        btnbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihActionPerformed(evt);
            }
        });
        jPanel4.add(btnbersih);

        paneldaftartugas.add(jPanel4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Daftar Tugas", paneldaftartugas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        ftmatkul.setText("");
        ftdead.setText("");
        ftdetail.setText("");
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String matkul = ftmatkul.getText();
        String dead = ftdead.getText();
        String detail = ftdetail.getText();
        
        String item = matkul + " ( Deadline : " + dead + " )";
        
        daftarTugas.add(detail);
        tugasModel.addElement(item);
        
        
        ftmatkul.setText("");
        ftdead.setText("");
        ftdetail.setText("");
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void listtugasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listtugasAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_listtugasAncestorAdded

    private void listtugasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listtugasValueChanged
        // TODO add your handling code here:
        int selectedIndex = listtugas.getSelectedIndex();

        // Menampilkan detail tugas yang sesuai dengan indeks yang dipilih
        if (selectedIndex >= 0) {
            String selectedDetail = daftarTugas.get(selectedIndex);
            fdetail.setText(selectedDetail);
        }
    }//GEN-LAST:event_listtugasValueChanged

    private void btnbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihActionPerformed
        // TODO add your handling code here:
        daftarTugas.clear();
        tugasModel.clear();
        fdetail.setText("");
    }//GEN-LAST:event_btnbersihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbersih;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JTextArea fdetail;
    private javax.swing.JTextField ftdead;
    private javax.swing.JTextArea ftdetail;
    private javax.swing.JTextField ftmatkul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listtugas;
    private javax.swing.JPanel paneldaftartugas;
    private javax.swing.JPanel paneltambahtugas;
    // End of variables declaration//GEN-END:variables
}
